/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto_pombo_so;

import static java.lang.Float.parseFloat;
import static java.lang.Integer.parseInt;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.concurrent.Semaphore;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.NumberFormatter;

/**
 *
 * @author Juan Igor
 */
public class JFrame_Execucao extends javax.swing.JFrame {
    
    private final int max_id = 24;
    private int maximo_msg, carga_pombo;
    private int qtd_user = 0;
    public static Semaphore EMPTY, FULL, MUTEX;
    private Pombo pombo;
    private ArrayList<Usuario> usuarios;
    private ArrayList<JLabel> user_labels, user_labels_id;
    private C_Msg caixa_msg, caixa_msg_destino;
    private final DefaultFormatterFactory mask_int = new DefaultFormatterFactory(new NumberFormatter(new DecimalFormat("#0")));
    private final DefaultFormatterFactory mask_float = new DefaultFormatterFactory(new NumberFormatter(new DecimalFormat("#0.00")));
    
    /**
     * Creates new form JFrame_Principal
     */
    public JFrame_Execucao() {
        setMax_msg();
        initComponents();
        setArrayUser();
        setCaixaMsg();
        setSemaphores();
        setLabels();
        jtaLog.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 13));
        jtaLog.setText("--> Programa inciado." + "\n");
        jtaLog.setText(jtaLog.getText() + "--> Quantidade de mensagens máx. da caixa: "+maximo_msg+" mensagens\n");
        
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jP_buttons = new javax.swing.JPanel();
        criar_pombo_btn = new javax.swing.JButton();
        criar_usuario_btn = new javax.swing.JButton();
        libertar_pombo_btn = new javax.swing.JButton();
        excluir_usuario_btn = new javax.swing.JButton();
        sair_btn = new javax.swing.JButton();
        jP_Log = new javax.swing.JPanel();
        jSP_Log = new javax.swing.JScrollPane();
        jtaLog = new javax.swing.JTextArea();
        jP_users = new javax.swing.JPanel();
        label_usuario3 = new javax.swing.JLabel();
        label_usuario1 = new javax.swing.JLabel();
        label_usuario2 = new javax.swing.JLabel();
        label_usuario4 = new javax.swing.JLabel();
        label_usuario5 = new javax.swing.JLabel();
        label_usuario6 = new javax.swing.JLabel();
        label_usuario7 = new javax.swing.JLabel();
        label_usuario8 = new javax.swing.JLabel();
        label_usuario9 = new javax.swing.JLabel();
        label_usuario10 = new javax.swing.JLabel();
        label_usuario11 = new javax.swing.JLabel();
        label_usuario12 = new javax.swing.JLabel();
        label_usuario13 = new javax.swing.JLabel();
        label_usuario14 = new javax.swing.JLabel();
        label_usuario15 = new javax.swing.JLabel();
        label_usuario16 = new javax.swing.JLabel();
        label_usuario17 = new javax.swing.JLabel();
        label_usuario18 = new javax.swing.JLabel();
        label_usuario19 = new javax.swing.JLabel();
        label_usuario20 = new javax.swing.JLabel();
        label_usuario21 = new javax.swing.JLabel();
        label_usuario22 = new javax.swing.JLabel();
        label_usuario23 = new javax.swing.JLabel();
        label_usuario24 = new javax.swing.JLabel();
        label_id24 = new javax.swing.JLabel();
        label_id23 = new javax.swing.JLabel();
        label_id19 = new javax.swing.JLabel();
        label_id20 = new javax.swing.JLabel();
        label_id21 = new javax.swing.JLabel();
        label_id22 = new javax.swing.JLabel();
        label_id6 = new javax.swing.JLabel();
        label_id5 = new javax.swing.JLabel();
        label_id4 = new javax.swing.JLabel();
        label_id3 = new javax.swing.JLabel();
        label_id2 = new javax.swing.JLabel();
        label_id1 = new javax.swing.JLabel();
        label_id7 = new javax.swing.JLabel();
        label_id8 = new javax.swing.JLabel();
        label_id9 = new javax.swing.JLabel();
        label_id10 = new javax.swing.JLabel();
        label_id11 = new javax.swing.JLabel();
        label_id12 = new javax.swing.JLabel();
        label_id13 = new javax.swing.JLabel();
        label_id14 = new javax.swing.JLabel();
        label_id15 = new javax.swing.JLabel();
        label_id16 = new javax.swing.JLabel();
        label_id17 = new javax.swing.JLabel();
        label_id18 = new javax.swing.JLabel();
        jP_simulation = new javax.swing.JPanel();
        label_mailbox1 = new javax.swing.JLabel();
        label_mailbox2 = new javax.swing.JLabel();
        label_pombo = new javax.swing.JLabel();
        jP_info = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        label_msg_armazenada = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        label_msg_enviada = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        qtd_usuarios = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        status_pombo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Projeto Pombo Correio - Execução");

        jP_buttons.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Menu", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP));

        criar_pombo_btn.setText("Criar Pombo");
        criar_pombo_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criar_pombo_btnActionPerformed(evt);
            }
        });

        criar_usuario_btn.setText("Criar Usuário");
        criar_usuario_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criar_usuario_btnActionPerformed(evt);
            }
        });

        libertar_pombo_btn.setText("Libertar Pombo");
        libertar_pombo_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                libertar_pombo_btnActionPerformed(evt);
            }
        });

        excluir_usuario_btn.setText("Excluir Usuário");
        excluir_usuario_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluir_usuario_btnActionPerformed(evt);
            }
        });

        sair_btn.setText("Sair do Programa");
        sair_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sair_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jP_buttonsLayout = new javax.swing.GroupLayout(jP_buttons);
        jP_buttons.setLayout(jP_buttonsLayout);
        jP_buttonsLayout.setHorizontalGroup(
            jP_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_buttonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(criar_pombo_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(criar_usuario_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(libertar_pombo_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(excluir_usuario_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sair_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jP_buttonsLayout.setVerticalGroup(
            jP_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_buttonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(libertar_pombo_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jP_buttonsLayout.createSequentialGroup()
                        .addGroup(jP_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(criar_pombo_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(criar_usuario_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(sair_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(excluir_usuario_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(1, 1, 1))
        );

        jP_Log.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Log de Eventos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP));

        jtaLog.setColumns(20);
        jtaLog.setLineWrap(true);
        jtaLog.setRows(5);
        jtaLog.setFocusable(false);
        jtaLog.setRequestFocusEnabled(false);
        jSP_Log.setViewportView(jtaLog);

        javax.swing.GroupLayout jP_LogLayout = new javax.swing.GroupLayout(jP_Log);
        jP_Log.setLayout(jP_LogLayout);
        jP_LogLayout.setHorizontalGroup(
            jP_LogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSP_Log)
        );
        jP_LogLayout.setVerticalGroup(
            jP_LogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSP_Log, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
        );

        jP_users.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Usuários", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP));

        label_usuario3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_usuario3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto_pombo_so/fotos/user_sleep.png"))); // NOI18N

        label_usuario1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_usuario1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto_pombo_so/fotos/user_sleep.png"))); // NOI18N
        label_usuario1.setDisabledIcon(null);

        label_usuario2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_usuario2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto_pombo_so/fotos/user_sleep.png"))); // NOI18N

        label_usuario4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_usuario4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto_pombo_so/fotos/user_sleep.png"))); // NOI18N
        label_usuario4.setDisabledIcon(null);

        label_usuario5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_usuario5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto_pombo_so/fotos/user_sleep.png"))); // NOI18N
        label_usuario5.setDisabledIcon(null);

        label_usuario6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_usuario6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto_pombo_so/fotos/user_sleep.png"))); // NOI18N
        label_usuario6.setDisabledIcon(null);

        label_usuario7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_usuario7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto_pombo_so/fotos/user_sleep.png"))); // NOI18N
        label_usuario7.setDisabledIcon(null);

        label_usuario8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_usuario8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto_pombo_so/fotos/user_sleep.png"))); // NOI18N
        label_usuario8.setDisabledIcon(null);

        label_usuario9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_usuario9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto_pombo_so/fotos/user_sleep.png"))); // NOI18N
        label_usuario9.setDisabledIcon(null);

        label_usuario10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_usuario10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto_pombo_so/fotos/user_sleep.png"))); // NOI18N
        label_usuario10.setDisabledIcon(null);

        label_usuario11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_usuario11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto_pombo_so/fotos/user_sleep.png"))); // NOI18N

        label_usuario12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_usuario12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto_pombo_so/fotos/user_sleep.png"))); // NOI18N

        label_usuario13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_usuario13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto_pombo_so/fotos/user_sleep.png"))); // NOI18N
        label_usuario13.setDisabledIcon(null);

        label_usuario14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_usuario14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto_pombo_so/fotos/user_sleep.png"))); // NOI18N
        label_usuario14.setDisabledIcon(null);

        label_usuario15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_usuario15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto_pombo_so/fotos/user_sleep.png"))); // NOI18N
        label_usuario15.setDisabledIcon(null);

        label_usuario16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_usuario16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto_pombo_so/fotos/user_sleep.png"))); // NOI18N

        label_usuario17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_usuario17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto_pombo_so/fotos/user_sleep.png"))); // NOI18N

        label_usuario18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_usuario18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto_pombo_so/fotos/user_sleep.png"))); // NOI18N
        label_usuario18.setDisabledIcon(null);

        label_usuario19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_usuario19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto_pombo_so/fotos/user_sleep.png"))); // NOI18N
        label_usuario19.setDisabledIcon(null);

        label_usuario20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_usuario20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto_pombo_so/fotos/user_sleep.png"))); // NOI18N

        label_usuario21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_usuario21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto_pombo_so/fotos/user_sleep.png"))); // NOI18N

        label_usuario22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_usuario22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto_pombo_so/fotos/user_sleep.png"))); // NOI18N
        label_usuario22.setDisabledIcon(null);

        label_usuario23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_usuario23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto_pombo_so/fotos/user_sleep.png"))); // NOI18N
        label_usuario23.setDisabledIcon(null);

        label_usuario24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_usuario24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto_pombo_so/fotos/user_sleep.png"))); // NOI18N
        label_usuario24.setDisabledIcon(null);

        label_id24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_id24.setText("ID: 24");

        label_id23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_id23.setText("ID: 23");

        label_id19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_id19.setText("ID: 19");

        label_id20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_id20.setText("ID: 20");

        label_id21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_id21.setText("ID: 21");

        label_id22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_id22.setText("ID: 22");

        label_id6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_id6.setText("ID: 6");

        label_id5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_id5.setText("ID: 5");

        label_id4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_id4.setText("ID: 4");

        label_id3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_id3.setText("ID: 3");

        label_id2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_id2.setText("ID: 2");

        label_id1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_id1.setText("ID: 1");

        label_id7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_id7.setText("ID: 7");

        label_id8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_id8.setText("ID: 8");

        label_id9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_id9.setText("ID: 9");

        label_id10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_id10.setText("ID: 10");

        label_id11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_id11.setText("ID: 11");

        label_id12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_id12.setText("ID: 12");

        label_id13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_id13.setText("ID: 13");

        label_id14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_id14.setText("ID: 14");

        label_id15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_id15.setText("ID: 15");

        label_id16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_id16.setText("ID: 16");

        label_id17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_id17.setText("ID: 17");

        label_id18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_id18.setText("ID: 18");

        javax.swing.GroupLayout jP_usersLayout = new javax.swing.GroupLayout(jP_users);
        jP_users.setLayout(jP_usersLayout);
        jP_usersLayout.setHorizontalGroup(
            jP_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_usersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jP_usersLayout.createSequentialGroup()
                        .addComponent(label_id7, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_id8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_id9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_id10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(2, 2, 2)
                        .addComponent(label_id11, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_id12, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jP_usersLayout.createSequentialGroup()
                        .addComponent(label_id1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_id2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_id3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_id4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(2, 2, 2)
                        .addComponent(label_id5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_id6, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jP_usersLayout.createSequentialGroup()
                        .addComponent(label_id19, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_id20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_id21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_id22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(2, 2, 2)
                        .addComponent(label_id23, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_id24, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jP_usersLayout.createSequentialGroup()
                        .addComponent(label_id13, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_id14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_id15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_id16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(2, 2, 2)
                        .addComponent(label_id17, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_id18, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jP_usersLayout.createSequentialGroup()
                        .addGroup(jP_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jP_usersLayout.createSequentialGroup()
                                .addComponent(label_usuario1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_usuario2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_usuario3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_usuario4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_usuario5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_usuario6))
                            .addGroup(jP_usersLayout.createSequentialGroup()
                                .addComponent(label_usuario7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_usuario8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_usuario9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_usuario10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_usuario11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_usuario12))
                            .addGroup(jP_usersLayout.createSequentialGroup()
                                .addComponent(label_usuario19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_usuario20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_usuario21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_usuario22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_usuario23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_usuario24))
                            .addGroup(jP_usersLayout.createSequentialGroup()
                                .addComponent(label_usuario13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_usuario14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_usuario15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_usuario16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_usuario17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_usuario18)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jP_usersLayout.setVerticalGroup(
            jP_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_usersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label_usuario6)
                    .addComponent(label_usuario5)
                    .addComponent(label_usuario4)
                    .addComponent(label_usuario2)
                    .addComponent(label_usuario1)
                    .addComponent(label_usuario3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_id6)
                    .addComponent(label_id5)
                    .addComponent(label_id1)
                    .addComponent(label_id2)
                    .addComponent(label_id3)
                    .addComponent(label_id4))
                .addGap(27, 27, 27)
                .addGroup(jP_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jP_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jP_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label_usuario8)
                            .addComponent(label_usuario9)
                            .addComponent(label_usuario7)
                            .addComponent(label_usuario10))
                        .addComponent(label_usuario12, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(label_usuario11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_id12)
                    .addComponent(label_id11)
                    .addComponent(label_id7)
                    .addComponent(label_id8)
                    .addComponent(label_id9)
                    .addComponent(label_id10))
                .addGap(28, 28, 28)
                .addGroup(jP_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label_usuario14)
                    .addComponent(label_usuario15)
                    .addComponent(label_usuario13)
                    .addComponent(label_usuario16)
                    .addComponent(label_usuario17)
                    .addComponent(label_usuario18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_id18)
                    .addComponent(label_id17)
                    .addComponent(label_id13)
                    .addComponent(label_id14)
                    .addComponent(label_id15)
                    .addComponent(label_id16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jP_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label_usuario24)
                    .addComponent(label_usuario23)
                    .addComponent(label_usuario22)
                    .addComponent(label_usuario20)
                    .addComponent(label_usuario19)
                    .addComponent(label_usuario21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_id24)
                    .addComponent(label_id23)
                    .addComponent(label_id19)
                    .addComponent(label_id20)
                    .addComponent(label_id21)
                    .addComponent(label_id22))
                .addContainerGap())
        );

        jP_simulation.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Simulação", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP));

        label_mailbox1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_mailbox1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto_pombo_so/fotos/mailbox_peq.png"))); // NOI18N

        label_mailbox2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_mailbox2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto_pombo_so/fotos/mailbox_peq.png"))); // NOI18N

        label_pombo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_pombo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto_pombo_so/fotos/pombo_sleep.png"))); // NOI18N

        javax.swing.GroupLayout jP_simulationLayout = new javax.swing.GroupLayout(jP_simulation);
        jP_simulation.setLayout(jP_simulationLayout);
        jP_simulationLayout.setHorizontalGroup(
            jP_simulationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_simulationLayout.createSequentialGroup()
                .addGroup(jP_simulationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label_pombo)
                    .addComponent(label_mailbox1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 319, Short.MAX_VALUE)
                .addComponent(label_mailbox2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jP_simulationLayout.setVerticalGroup(
            jP_simulationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_simulationLayout.createSequentialGroup()
                .addComponent(label_pombo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP_simulationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label_mailbox2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_mailbox1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jP_info.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Info", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Quantidade de mensagens armazenadas:");

        label_msg_armazenada.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label_msg_armazenada.setText("0");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Quantidade de mensagens enviadas:");

        label_msg_enviada.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label_msg_enviada.setText("0");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Quantidade de usuários:");

        qtd_usuarios.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        qtd_usuarios.setText("0");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Status Pombo:");

        status_pombo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        status_pombo.setText("Pombo não existe...");

        javax.swing.GroupLayout jP_infoLayout = new javax.swing.GroupLayout(jP_info);
        jP_info.setLayout(jP_infoLayout);
        jP_infoLayout.setHorizontalGroup(
            jP_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_infoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jP_infoLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(label_msg_enviada))
                    .addGroup(jP_infoLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(qtd_usuarios))
                    .addGroup(jP_infoLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(status_pombo))
                    .addGroup(jP_infoLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(label_msg_armazenada)))
                .addContainerGap(236, Short.MAX_VALUE))
        );
        jP_infoLayout.setVerticalGroup(
            jP_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_infoLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jP_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(label_msg_armazenada))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(label_msg_enviada))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(qtd_usuarios))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(status_pombo))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jP_buttons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jP_users, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jP_info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jP_Log, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jP_simulation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jP_buttons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jP_simulation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jP_Log, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jP_info, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jP_users, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void excluir_usuario_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluir_usuario_btnActionPerformed
        // TODO add your handling code here:
        excluir_usuario();
    }//GEN-LAST:event_excluir_usuario_btnActionPerformed

    private void sair_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sair_btnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_sair_btnActionPerformed

    private void libertar_pombo_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_libertar_pombo_btnActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(null, "Deseja realmente libertar o pombo?\nPS.: O pombo só irá ser libertado após completar o seu voo!", "Libertar o Pombo", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            jtaLog.setText(jtaLog.getText() + "--> Pombo libertado." + "\n");
            pombo.libertar_pombo();
        }
    }//GEN-LAST:event_libertar_pombo_btnActionPerformed

    private void criar_usuario_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criar_usuario_btnActionPerformed
        // TODO add your handling code here:
        criar_usuario();
    }//GEN-LAST:event_criar_usuario_btnActionPerformed

    private void criar_pombo_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criar_pombo_btnActionPerformed
        // TODO add your handling code here:
        criar_pombo();
    }//GEN-LAST:event_criar_pombo_btnActionPerformed
    
    private void setLabels(){
        user_labels = new ArrayList<JLabel>();
        user_labels.add(label_usuario1);
        user_labels.add(label_usuario2);
        user_labels.add(label_usuario3);
        user_labels.add(label_usuario4);
        user_labels.add(label_usuario5);
        user_labels.add(label_usuario6);
        user_labels.add(label_usuario7);
        user_labels.add(label_usuario8);
        user_labels.add(label_usuario9);
        user_labels.add(label_usuario10);
        user_labels.add(label_usuario11);
        user_labels.add(label_usuario12);
        user_labels.add(label_usuario13);
        user_labels.add(label_usuario14);
        user_labels.add(label_usuario15);
        user_labels.add(label_usuario16);
        user_labels.add(label_usuario17);
        user_labels.add(label_usuario18);
        user_labels.add(label_usuario19);
        user_labels.add(label_usuario20);
        user_labels.add(label_usuario21);
        user_labels.add(label_usuario22);
        user_labels.add(label_usuario23);
        user_labels.add(label_usuario24);
//        user_labels.add(label_usuario25);
//        user_labels.add(label_usuario26);
//        user_labels.add(label_usuario27);
//        user_labels.add(label_usuario28);
//        user_labels.add(label_usuario29);
//        user_labels.add(label_usuario30);
//        user_labels.add(label_usuario31);
//        user_labels.add(label_usuario32);
//        user_labels.add(label_usuario33);
//        user_labels.add(label_usuario34);
//        user_labels.add(label_usuario35);
//        user_labels.add(label_usuario36);
        for(JLabel label: user_labels){
            label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto_pombo_so/fotos/fundo72x72.png")));
        }
        label_pombo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto_pombo_so/fotos/fundo72x72.png")));
        
        user_labels_id = new ArrayList<JLabel>();
        user_labels_id.add(label_id1);
        user_labels_id.add(label_id2);
        user_labels_id.add(label_id3);
        user_labels_id.add(label_id4);
        user_labels_id.add(label_id5);
        user_labels_id.add(label_id6);
        user_labels_id.add(label_id7);
        user_labels_id.add(label_id8);
        user_labels_id.add(label_id9);
        user_labels_id.add(label_id10);
        user_labels_id.add(label_id11);
        user_labels_id.add(label_id12);
        user_labels_id.add(label_id13);
        user_labels_id.add(label_id14);
        user_labels_id.add(label_id15);
        user_labels_id.add(label_id16);
        user_labels_id.add(label_id17);
        user_labels_id.add(label_id18);
        user_labels_id.add(label_id19);
        user_labels_id.add(label_id20);
        user_labels_id.add(label_id21);
        user_labels_id.add(label_id22);
        user_labels_id.add(label_id23);
        user_labels_id.add(label_id24);
        for(JLabel label : user_labels_id){
            label.setText("");
        }
    }
    
    private void setSemaphores(){
        EMPTY = new Semaphore(maximo_msg);
        FULL = new Semaphore(0);
        MUTEX = new Semaphore(1);
    }
    
    private void setMax_msg(){
        boolean loop = true;
        boolean exit = false;
        JFormattedTextField jtf_qtd = new JFormattedTextField();
        jtf_qtd.setFormatterFactory(mask_int);
        Object[] msg = {
            "Digite a quantidade de mensagens que a caixa irá armazenar:", jtf_qtd
        };
        while(loop){
            int result = JOptionPane.showConfirmDialog(null, msg, "Atenção!", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
            jtf_qtd.requestFocus();
            if(result == JOptionPane.OK_OPTION){
                if(jtf_qtd.getText().isEmpty()){
                    JOptionPane.showMessageDialog(null, "Erro! É Necessário digitar a quantidade de mensagens!!\nDigite novamente...", "Atenção", JOptionPane.INFORMATION_MESSAGE);
                }
                else{
                    maximo_msg = parseInt(jtf_qtd.getText());
                    loop = false;
                }
            }
            else{
                loop = false;
                exit = true;
            }
        }
        if(exit){ System.exit(0); }
    }
    
    private void setCaixaMsg(){
        caixa_msg = new C_Msg(label_msg_armazenada, maximo_msg);
        caixa_msg_destino = new C_Msg(label_msg_enviada, Integer.MAX_VALUE);
    }
    
    private void setArrayUser(){
        usuarios = new ArrayList<Usuario>();
        for(int i=0; i<max_id; i++){
            usuarios.add(null);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {;
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_Execucao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_Execucao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_Execucao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_Execucao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_Execucao();
            }
        });
    }
    
    private void criar_usuario(){
        // <editor-fold defaultstate="collapsed" desc=" Código JPanel Usuário ">
        JPanel panel_cUser = new JPanel();
        JLabel label_escrita = new JLabel();
        JLabel label_id = new JLabel();
        JLabel label_img = new JLabel();
        JLabel label_s = new JLabel();
        JFormattedTextField jtf_id = new JFormattedTextField();
        JFormattedTextField jtf_escrita = new JFormattedTextField();
        
        label_escrita.setFont(new java.awt.Font("Tahoma", 0, 14));
        label_escrita.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_escrita.setText("Tempo de escrita (segundos):");

        label_id.setFont(new java.awt.Font("Tahoma", 0, 14));
        label_id.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_id.setText("Identificador (ID):");
        
        label_s.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label_s.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_s.setText("s");
        
        label_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto_pombo_so/fotos/add_peq.png")));
        
        jtf_id.setFormatterFactory(mask_int);
        jtf_id.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtf_id.setFont(new java.awt.Font("Tahoma", 0, 14));

        jtf_escrita.setFormatterFactory(mask_float);
        jtf_escrita.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtf_escrita.setFont(new java.awt.Font("Tahoma", 0, 14));
        
        javax.swing.GroupLayout panel_cUserLayout = new javax.swing.GroupLayout(panel_cUser);
        panel_cUser.setLayout(panel_cUserLayout);
        panel_cUserLayout.setHorizontalGroup(
            panel_cUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cUserLayout.createSequentialGroup()
                .addGroup(panel_cUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_cUserLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panel_cUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panel_cUserLayout.createSequentialGroup()
                                .addComponent(label_escrita)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtf_escrita, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_s))
                            .addGroup(panel_cUserLayout.createSequentialGroup()
                                .addComponent(label_id)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtf_id))))
                    .addGroup(panel_cUserLayout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(label_img)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_cUserLayout.setVerticalGroup(
            panel_cUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_cUserLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label_img)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_cUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_id)
                    .addComponent(jtf_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_cUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_escrita)
                    .addComponent(jtf_escrita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_s))
                .addContainerGap())
        );// </editor-fold>
        
        boolean inLoop = true;
        while(inLoop){
            int result = JOptionPane.showConfirmDialog(null, panel_cUser, "Criar Usuário", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
            if(result == JOptionPane.OK_OPTION){
                if(jtf_id.getText().isEmpty() && jtf_escrita.getText().isEmpty()){
                    JOptionPane.showMessageDialog(null, "Erro! Nenhum campo preenchido.", "Atenção", JOptionPane.INFORMATION_MESSAGE);
                }
                else if(jtf_id.getText().isEmpty()){
                    JOptionPane.showMessageDialog(null, "Erro! Campo 'Identificador' não preenchido.", "Atenção", JOptionPane.INFORMATION_MESSAGE);
                }
                else if(parseInt(jtf_id.getText()) > max_id){
                    JOptionPane.showMessageDialog(null, "Erro! Só podem ser definidos ID's de 1 a "+max_id+".", "Atenção", JOptionPane.INFORMATION_MESSAGE);
                }
                else if(usuarios.get(parseInt(jtf_id.getText())-1) != null){
                    JOptionPane.showMessageDialog(null, "Erro! ID já existente.", "Atenção", JOptionPane.INFORMATION_MESSAGE);
                }
                else if(jtf_escrita.getText().isEmpty()){
                    JOptionPane.showMessageDialog(null, "Erro! Campo 'Tempo de escrita' não preenchido.", "Atenção", JOptionPane.INFORMATION_MESSAGE);
                }
                else{
                    int id = parseInt(jtf_id.getText());
                    float te = parseFloat(jtf_escrita.getText().replace(',', '.'));
                    
                    if(id <= 0 || te <= 0){
                        JOptionPane.showMessageDialog(null, "Erro! Nenhum campo pode ser preenchido com o valor 0 ou menor.", "Atenção", JOptionPane.INFORMATION_MESSAGE);
                    }
                    else{
                        qtd_user++;
                        qtd_usuarios.setText(""+qtd_user);
                        JLabel temp_label = user_labels.get(id-1);
                        JLabel temp_label2 = user_labels_id.get(id-1);
                        temp_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto_pombo_so/fotos/user_sleep.png")));
                        temp_label2.setText("ID: "+id);
                        Usuario temp_user = new Usuario(caixa_msg, temp_label, temp_label2, id, te);
                        jtaLog.setText(jtaLog.getText() + "--> Usuário ID:"+id+" criado --> Tempo de Escrita:"+jtf_escrita.getText()+"s\n");
                        usuarios.set(id-1, temp_user);
                        
                        temp_user.start();
                        inLoop = false;
                    }
                }
            }
            else{ inLoop = false; }
        }
    }
    
    private void criar_pombo(){
        //<editor-fold defaultstate="collapsed" desc=" Código JPanel Pombo ">
        JPanel panel_cPombo = new JPanel();
        JLabel label_img = new JLabel();
        JLabel label_carga = new JLabel();
        JLabel label_voo = new JLabel();
        JLabel label_descarga = new JLabel();
        JLabel label_carga_max = new JLabel();
        JLabel label_s1 = new JLabel();
        JLabel label_s2 = new JLabel();
        JLabel label_s3 = new JLabel();
        JLabel label_msgs = new JLabel();
        JFormattedTextField jtf_carga = new JFormattedTextField();
        JFormattedTextField jtf_voo = new JFormattedTextField();
        JFormattedTextField jtf_descarga = new JFormattedTextField();
        JFormattedTextField jtf_msgs = new JFormattedTextField();
        
        label_carga.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label_carga.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_carga.setText("Tempo de carga (segundos):");

        label_voo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label_voo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_voo.setText("Tempo de voo (segundos):");

        jtf_voo.setFormatterFactory(mask_float);
        jtf_voo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtf_voo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jtf_carga.setFormatterFactory(mask_float);
        jtf_carga.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtf_carga.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        label_s2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label_s2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_s2.setText("s");

        label_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto_pombo_so/fotos/add_peq.png"))); // NOI18N

        label_s1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label_s1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_s1.setText("s");

        label_s3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label_s3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_s3.setText("s");

        jtf_descarga.setFormatterFactory(mask_float);
        jtf_descarga.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtf_descarga.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        label_descarga.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label_descarga.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_descarga.setText("Tempo de descarga (segundos):");

        label_msgs.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label_msgs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_msgs.setText("msg's");

        label_carga_max.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label_carga_max.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_carga_max.setText("Carga Máxima (qtd. máx. de msg.):");

        jtf_msgs.setFormatterFactory(mask_int);
        jtf_msgs.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtf_msgs.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout panel_cPomboLayout = new javax.swing.GroupLayout(panel_cPombo);
        panel_cPombo.setLayout(panel_cPomboLayout);
        panel_cPomboLayout.setHorizontalGroup(
            panel_cPomboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cPomboLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_cPomboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panel_cPomboLayout.createSequentialGroup()
                        .addGroup(panel_cPomboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_cPomboLayout.createSequentialGroup()
                                .addComponent(label_carga)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtf_carga))
                            .addGroup(panel_cPomboLayout.createSequentialGroup()
                                .addComponent(label_voo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtf_voo)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_cPomboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_s2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label_s1, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(panel_cPomboLayout.createSequentialGroup()
                        .addComponent(label_descarga)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtf_descarga)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_s3))
                    .addGroup(panel_cPomboLayout.createSequentialGroup()
                        .addComponent(label_carga_max)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtf_msgs, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_msgs)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_cPomboLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(label_img)
                .addGap(162, 162, 162))
        );
        panel_cPomboLayout.setVerticalGroup(
            panel_cPomboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_cPomboLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_img)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_cPomboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_voo)
                    .addComponent(jtf_voo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_s1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_cPomboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_carga)
                    .addComponent(jtf_carga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_s2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_cPomboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_descarga)
                    .addComponent(jtf_descarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_s3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_cPomboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_carga_max)
                    .addComponent(jtf_msgs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_msgs))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );// </editor-fold>
        
        boolean inLoop = true;
        while(inLoop){
            int result = JOptionPane.showConfirmDialog(null, panel_cPombo, "Criar Pombo", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
            if(result == JOptionPane.OK_OPTION){
                if(jtf_voo.getText().isEmpty() && jtf_carga.getText().isEmpty() &&
                   jtf_descarga.getText().isEmpty() && jtf_msgs.getText().isEmpty()){
                    JOptionPane.showMessageDialog(null, "Erro! Nenhum campo preenchido.", "Atenção", JOptionPane.INFORMATION_MESSAGE);
                }
                else if(jtf_voo.getText().isEmpty()){
                    JOptionPane.showMessageDialog(null, "Erro! Campo 'Tempo de Voo' não preenchido.", "Atenção", JOptionPane.INFORMATION_MESSAGE);
                }
                else if(jtf_carga.getText().isEmpty()){
                    JOptionPane.showMessageDialog(null, "Erro! Campo 'Tempo de Carga' não preenchido.", "Atenção", JOptionPane.INFORMATION_MESSAGE);
                }
                else if(jtf_descarga.getText().isEmpty()){
                    JOptionPane.showMessageDialog(null, "Erro! Campo 'Tempo de Descarga' não preenchido.", "Atenção", JOptionPane.INFORMATION_MESSAGE);
                }
                else if(jtf_msgs.getText().isEmpty()){
                    JOptionPane.showMessageDialog(null, "Erro! Campo 'Carga Máxima' não preenchido.", "Atenção", JOptionPane.INFORMATION_MESSAGE);
                }
                else if(parseInt(jtf_msgs.getText()) > maximo_msg){
                    JOptionPane.showMessageDialog(null, "Erro! A carga máxima do pombo excede a\ncapacidade da caixa de mensagens.", "Atenção", JOptionPane.INFORMATION_MESSAGE);
                }
                else{
                    float tv = parseFloat(jtf_voo.getText().replace(',', '.'));
                    float tc = parseFloat(jtf_carga.getText().replace(',', '.'));
                    float td = parseFloat(jtf_descarga.getText().replace(',', '.'));
                    carga_pombo = parseInt(jtf_msgs.getText());
                    
                    if(carga_pombo <= 0 || tv <= 0 || tc <= 0 || td <= 0){
                        JOptionPane.showMessageDialog(null, "Erro! Nenhum campo pode ser preenchido com o valor 0 ou menor.", "Atenção", JOptionPane.INFORMATION_MESSAGE);
                    }
                    else{
                        pombo = new Pombo(status_pombo, caixa_msg, caixa_msg_destino, 391, carga_pombo, tc, td, tv);
                        criar_usuario_btn.setEnabled(true);
                        label_pombo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto_pombo_so/fotos/pombo_sleep.png")));
                        status_pombo.setText("Pombo Criado...");
                        jtaLog.setText(jtaLog.getText() + "--> Pombo criado --> T.C.: "+jtf_carga.getText()+"s T.D.: "+jtf_descarga.getText()+"s T.V.: "+jtf_voo.getText()+"s Max. Carga: "+jtf_msgs.getText()+"\n");
                        pombo.start();
                        inLoop = false;
                    }
                }
            }
            else{ inLoop = false; }
        }
    }
    
    private void excluir_usuario(){
        //<editor-fold defaultstate="collapsed" desc=" Código JPanel Excluir Usuário ">
        JPanel panel_eUser = new JPanel();
        JLabel label_img = new JLabel();
        JLabel label_id = new JLabel();
        JFormattedTextField jtf_id = new JFormattedTextField();
        label_id.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label_id.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_id.setText("Identificador (ID):");

        jtf_id.setFormatterFactory(mask_int);
        jtf_id.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtf_id.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        label_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto_pombo_so/fotos/delete_peq.png"))); // NOI18N

        javax.swing.GroupLayout panel_eUserLayout = new javax.swing.GroupLayout(panel_eUser);
        panel_eUser.setLayout(panel_eUserLayout);
        panel_eUserLayout.setHorizontalGroup(
            panel_eUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_eUserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_id)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf_id, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_eUserLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label_img)
                .addGap(92, 92, 92))
        );
        panel_eUserLayout.setVerticalGroup(
            panel_eUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_eUserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_img)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_eUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_id)
                    .addComponent(jtf_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );//</editor-fold>
        
        boolean inLoop = true;
        while(inLoop){
            int result = JOptionPane.showConfirmDialog(null, panel_eUser, "Exluir Usuário", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
            if(result == JOptionPane.OK_OPTION){
                if(jtf_id.getText().isEmpty()){
                    JOptionPane.showMessageDialog(null, "Erro! Campo 'Identificador' não preenchido.", "Atenção", JOptionPane.INFORMATION_MESSAGE);
                }
                else if(parseInt(jtf_id.getText()) <= 0 || parseInt(jtf_id.getText()) > max_id){
                    JOptionPane.showMessageDialog(null, "Erro! ID fora do escopo.\nEscopo: 1 a "+max_id+"!!", "Atenção", JOptionPane.INFORMATION_MESSAGE);
                }
                else{
                    int id = parseInt(jtf_id.getText());
                    jtaLog.setText(jtaLog.getText() + "--> Usuário ID:"+id+" excluido." + "\n");
                    usuarios.get(id-1).excluir_usuario();
                    usuarios.set(id-1, null);
                    user_labels.get(id-1).setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto_pombo_so/fotos/fundo72x72.png")));
                    user_labels_id.get(id-1).setText("");
                    qtd_user--;
                    qtd_usuarios.setText(""+qtd_user);
                    inLoop = false;
                }
            }
            else{ inLoop = false; }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton criar_pombo_btn;
    private javax.swing.JButton criar_usuario_btn;
    private javax.swing.JButton excluir_usuario_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jP_Log;
    private javax.swing.JPanel jP_buttons;
    private javax.swing.JPanel jP_info;
    private javax.swing.JPanel jP_simulation;
    private javax.swing.JPanel jP_users;
    private javax.swing.JScrollPane jSP_Log;
    private javax.swing.JTextArea jtaLog;
    private javax.swing.JLabel label_id1;
    private javax.swing.JLabel label_id10;
    private javax.swing.JLabel label_id11;
    private javax.swing.JLabel label_id12;
    private javax.swing.JLabel label_id13;
    private javax.swing.JLabel label_id14;
    private javax.swing.JLabel label_id15;
    private javax.swing.JLabel label_id16;
    private javax.swing.JLabel label_id17;
    private javax.swing.JLabel label_id18;
    private javax.swing.JLabel label_id19;
    private javax.swing.JLabel label_id2;
    private javax.swing.JLabel label_id20;
    private javax.swing.JLabel label_id21;
    private javax.swing.JLabel label_id22;
    private javax.swing.JLabel label_id23;
    private javax.swing.JLabel label_id24;
    private javax.swing.JLabel label_id3;
    private javax.swing.JLabel label_id4;
    private javax.swing.JLabel label_id5;
    private javax.swing.JLabel label_id6;
    private javax.swing.JLabel label_id7;
    private javax.swing.JLabel label_id8;
    private javax.swing.JLabel label_id9;
    private javax.swing.JLabel label_mailbox1;
    private javax.swing.JLabel label_mailbox2;
    private javax.swing.JLabel label_msg_armazenada;
    private javax.swing.JLabel label_msg_enviada;
    public static javax.swing.JLabel label_pombo;
    private javax.swing.JLabel label_usuario1;
    private javax.swing.JLabel label_usuario10;
    private javax.swing.JLabel label_usuario11;
    private javax.swing.JLabel label_usuario12;
    private javax.swing.JLabel label_usuario13;
    private javax.swing.JLabel label_usuario14;
    private javax.swing.JLabel label_usuario15;
    private javax.swing.JLabel label_usuario16;
    private javax.swing.JLabel label_usuario17;
    private javax.swing.JLabel label_usuario18;
    private javax.swing.JLabel label_usuario19;
    private javax.swing.JLabel label_usuario2;
    private javax.swing.JLabel label_usuario20;
    private javax.swing.JLabel label_usuario21;
    private javax.swing.JLabel label_usuario22;
    private javax.swing.JLabel label_usuario23;
    private javax.swing.JLabel label_usuario24;
    private javax.swing.JLabel label_usuario3;
    private javax.swing.JLabel label_usuario4;
    private javax.swing.JLabel label_usuario5;
    private javax.swing.JLabel label_usuario6;
    private javax.swing.JLabel label_usuario7;
    private javax.swing.JLabel label_usuario8;
    private javax.swing.JLabel label_usuario9;
    private javax.swing.JButton libertar_pombo_btn;
    private javax.swing.JLabel qtd_usuarios;
    private javax.swing.JButton sair_btn;
    private javax.swing.JLabel status_pombo;
    // End of variables declaration//GEN-END:variables
}
